### ISSUE TITLE
绘制过程中获取数据的数组大小不符合

### ISSUE THREAD

**Issue by pokedo0** [mcxtzhang/Demos#1]
在Recyclerview 上滑过程清除包含数据的datalist再重新加载新数据过程中，数据还没添加完就已经执行了onDraw方法，抛出了异常 # @mcxtzhang

**Comment by pokedo0** [comment]
Process: com.example.delitto.myapplication, PID: 3227
                  java.lang.IndexOutOfBoundsException: Index: 24, Size: 0
                      at java.util.ArrayList.get(ArrayList.java:411)
                      at com.example.delitto.myapplication.decoration.TitleItemDecoration.onDraw(TitleItemDecoration.java:62)
                      at android.support.v7.widget.RecyclerView.onDraw(RecyclerView.java:3722)

代码处:
                   if (null != mDatas.get(position).getDate() && !mDatas.get(position).getDate().equals(mDatas.get(position - 1).getDate())) {
                        //不为空 且跟前一个tag不一样了，说明是新的分类，也要title
                        drawTitleArea(c, left, right, child, params, position);
                    } else {
                        //none
                    }

**Comment by mcxtzhang** [comment]
ItemDecoration的移步：https://github.com/mcxtzhang/SuspensionIndexBar
